[package]
name = "ues"
version = "2.2.1"
authors = ["Earl Dukerschein<earl.dukerschein@wisc.edu>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7.3"
rayon = "1.5"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.8"
readonly = "0.2"
