[package]
name = "ues"
version = "2.3.8"
authors = ["Bitflogger<earl.dukerschein@wisc.edu>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
rayon = "1.5.3"
serde = { version = "1.0.145", features = ["derive"] }
serde_yaml = "0.9.13"
readonly = "0.2.2"
